name: common
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  client_data:
    git:
      url: https://github.com/dart-lang/pub-dev.git
      path: pkg/client_data

  json_annotation: ^3.0.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
  build_runner: ^1.0.0
  json_serializable: ^3.0.0